# vst_helper/generators.py
GENERATED_HEADER = "# GENERATED by VST Helper -- do not edit; changes will be overwritten.\n"


def write_yabridge_toml(directory: Path, plugins: list[Plugin]) -> Path:
    """Emit one merged yabridge.toml per physical directory.
    Same-directory plugins are merged into per-plugin sections — never
    emit overlapping files at different depths."""
    path = directory / "yabridge.toml"
    lines = [GENERATED_HEADER]
    for plugin in sorted(plugins, key=lambda p: p.name):
        slug = slugify(plugin.name)
        lines.append(f"[plugins.'{slug}']")
        lines.append(f'group = "{slugify(plugin.group)}"')
        for key, value in plugin.yabridge_options.items():
            lines.append(f'{slugify(key)} = "{value}"')
        lines.append("")
    path.write_text("\n".join(lines))
    return path
